### ISSUE TITLE
[Question] How are css being managed in this app 

### ISSUE THREAD

**Issue by saiyeek** [Rhadow/redux-example#1]
Hi,
I came here following a link in awesome-redux. I am learning redux and I stumbled upon this example. Could you please tell me how component specific styles are managed in this example? 
Thanks.

**Comment by Rhadow** [comment]
With webpack, you can import css file inside your component as shown in here: https://github.com/Rhadow/redux-example/blob/master/src/components/WeatherMap/WeatherMap.js#L1. 
In my case, it is a sass file. 

Webpack then compiles it into css and add these styles in a style tag with different webpack loader during development. Webpack can also produce a separate css file with some adjustment in configuration.

**Comment by saiyeek** [comment]
Thankds Rhadow,
That was very helpful. I am new to this ecosystem with webpack. That definitely helped.
